spring.datasource.url=jdbc:sqlite:smart-finance.db
spring.datasource.driver-class-name=org.sqlite.JDBC

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.community.dialect.SQLiteDialect

cloudinary.cloud-name=${CLOUDINARY_CLOUD_NAME:dxkw3nupk}
cloudinary.api-key=${CLOUDINARY_API_KEY:628636577581966}
cloudinary.api-secret=${CLOUDINARY_API_SECRET:rFh3fRsPzKxdhDax-FH-mHhmOmc}